"""Bilingual text dictionary and localization helpers for 8-Puzzle UI."""

from __future__ import annotations

import eight_puzzle_search_app as puzzle
from typing import Any, Dict

TEXT: Dict[str, Dict[str, str]] = {
    "vi": {
        "page_title": "Phòng thí nghiệm tìm kiếm 8-Puzzle",
        "page_subtitle": "Trực quan hóa BFS, UCS, A*, IDA* và các thuật toán tìm kiếm cục bộ trên cùng một ma trận.",
        "advanced_settings": "Thiết lập nâng cao",
        "result_details": "Bảng kết quả chi tiết",
        "summary_tab": "Tổng quan",
        "academic_trace_tab": "Trace học thuật",
        "heuristics_tab": "Phân tích heuristic",
        "experiment_tab": "Thử nghiệm",
        "path_player_tab": "Phát lại đường đi",
        "report_tab": "Báo cáo",
        "controls": "Điều khiển",
        "language": "Ngôn ngữ / Language",
        "algorithm": "Thuật toán",
        "algorithm_group": "Nhóm thuật toán",
        "heuristic": "Hàm heuristic",
        "seed": "Seed",
        "scramble_moves": "Số bước tự trộn",
        "shuffle": "Tự trộn ma trận",
        "max_expansions": "Giới hạn mở rộng node",
        "max_trace_rows": "Số dòng trace tối đa",
        "frontier_preview": "Số frontier xem trước",
        "reached_preview": "Số reached xem trước",
        "ids_depth": "Độ sâu IDS tối đa",
        "ida_iterations": "Số vòng IDA*",
        "local_steps": "Số bước local tối đa",
        "random_restarts": "Số lần random restart",
        "beam_width": "Độ rộng beam",
        "board_panel": "Ma trận 8-puzzle",
        "initial_shuffle": "Trạng thái bắt đầu hiện tại được tự trộn 20 bước từ đích.",
        "shuffle_note": "Đã tự trộn ma trận {moves} bước từ đích (seed={seed}, lần {count}).",
        "demo_preset": "Mẫu có sẵn",
        "load_preset": "Dùng mẫu",
        "preset_note": "Đang dùng mẫu demo: {name}.",
        "start_state": "Trạng thái bắt đầu",
        "goal_state": "Trạng thái đích",
        "goal_caption": "Đích cố định: đưa ô trống 0 về góc dưới bên phải.",
        "goal_and_input": "Đích và nhập tay",
        "custom_start": "Nhập ma trận bắt đầu",
        "custom_help": "Nhập 9 số từ 0 đến 8, ví dụ: 1 2 3 4 5 6 0 7 8",
        "use_custom": "Dùng ma trận này",
        "run": "Chạy thuật toán",
        "run_selected": "Chạy thuật toán đã chọn",
        "compare_all": "So sánh nhóm đang chọn",
        "notes": (
            "UCS dùng chi phí mỗi bước bằng 1 nên thường cho độ dài nghiệm giống BFS. "
            "A* với Manhattan tối ưu vì Manhattan là heuristic chấp nhận được cho 8-puzzle. "
            "Tham lam có thể nhanh nhưng không đảm bảo tối ưu. "
            "Leo đồi và tìm kiếm chùm cục bộ có thể kẹt ở cực trị cục bộ hoặc vùng bằng phẳng."
        ),
        "choose_action": "Chọn một thao tác trong vùng chạy thuật toán.",
        "run_summary": "Bảng tổng kết",
        "final_state": "Trạng thái cuối",
        "best_final_state": "Trạng thái tốt nhất / cuối hiện tại",
        "solution_path": "Các bước lời giải",
        "step": "Bước",
        "start": "Bắt đầu",
        "trace": "Bảng Node / Frontier / Reached đầy đủ",
        "algorithm_certificate": "Chứng nhận thuật toán",
        "certificate_status": "Trạng thái kiểm chứng",
        "certificate_pass": "Đạt",
        "certificate_fail": "Lỗi",
        "heuristic_inspector": "Bộ phân tích heuristic",
        "heuristic_totals": "Tổng hợp heuristic",
        "tile_contributions": "Đóng góp từng ô",
        "linear_conflicts": "Các cặp Linear Conflict",
        "no_linear_conflicts": "Không có cặp Linear Conflict trong trạng thái này.",
        "trace_story": "Vì sao chọn node này?",
        "experiment_lab": "Phòng thử nghiệm",
        "run_experiment": "Chạy phòng thử nghiệm",
        "download_experiment": "Tải báo cáo thử nghiệm",
        "path_playback": "Phát lại đường đi",
        "coursework_report": "Báo cáo bài làm",
        "download_report": "Tải báo cáo Markdown",
        "report_preview": "Nội dung báo cáo",
        "benchmark": "Đo hiệu năng demo nhỏ",
        "run_benchmark": "Chạy đo hiệu năng mẫu",
        "benchmark_caption": "Benchmark dùng preset cố định và tắt trace để đo nhanh, phù hợp đưa vào báo cáo.",
        "comparison": "Bảng so sánh thuật toán",
        "academic_panel": "Cơ sở học thuật",
        "grading_checklist": "Checklist nộp bài",
        "heuristic_usage": "Cách dùng h(n)",
        "demo_readiness": "Trạng thái demo",
        "run_mode": "Kiểu chạy",
        "solvable": "Có lời giải",
        "unsolvable": "Không có lời giải",
        "current_preset": "Mẫu hiện tại",
        "selected_heuristic": "Hàm h(n)",
        "trace_player": "Trình phát trace học thuật",
        "trace_replay_row": "Dòng trace cần xem",
        "selected_node": "Node đang xét",
        "frontier_after": "Frontier sau mở rộng",
        "reached_after": "Reached sau mở rộng",
        "generated_skipped": "Đã sinh / Bỏ qua",
        "search_tree_preview": "Xem trước cây tìm kiếm",
        "peas_model": "PEAS",
        "problem_variant": "Dạng bài toán theo thuật toán",
        "problem_definition": "Mô hình bài toán",
        "algorithm_profile": "Hồ sơ thuật toán đang chọn",
        "evaluation_criteria": "Tiêu chí đánh giá",
        "trace_glossary": "Ý nghĩa Node / Frontier / Reached",
        "objective": "Mục tiêu",
        "state_space": "Không gian trạng thái",
        "transition_model": "Mô hình chuyển trạng thái",
        "heuristic_formula": "Công thức heuristic",
        "priority_basis": "Cơ sở ưu tiên g(n), h(n), f(n)",
        "primary_basis": "Dựa chính trên",
        "priority_rule": "Quy tắc ưu tiên",
        "uses_component": "Có dùng?",
        "component_meaning": "Ý nghĩa trong thuật toán đang chọn",
        "yes": "Có",
        "no": "Không",
        "implicit": "Gián tiếp",
        "path_player": "Theo dõi đường đi từng bước",
        "previous_step": "Bước trước",
        "next_step": "Bước sau",
        "step_slider": "Chọn bước cần quan sát",
        "before_move": "Trạng thái trước bước đi",
        "after_move": "Trạng thái hiện tại",
        "current_action": "Hành động vừa thực hiện",
        "next_action": "Hành động tiếp theo",
        "route_sequence": "Chuỗi hành động",
        "route_table": "Bảng đường đi đầy đủ",
        "no_solution_path": "Thuật toán chưa tìm được đường đi tới Goal nên không có bước để phát lại.",
        "total_steps": "Tổng số bước",
        "sa_initial_temp": "Nhiệt độ ban đầu SA",
        "sa_cooling_rate": "Tỷ lệ làm nguội",
        "sa_min_temp": "Nhiệt độ tối thiểu",
        "sa_max_steps": "Số bước SA tối đa",
        "app_kicker": "Trình trực quan hóa tìm kiếm AI",
        "state_lab": "phòng trạng thái",
        "algorithm_cockpit": "bảng điều khiển thuật toán",
        "random_manual": "Ngẫu nhiên/nhập tay",
        "path_length": "Độ dài đường đi",
        "expanded_metric": "Đã mở rộng",
        "generated_metric": "Đã sinh",
        "runtime_metric": "Thời gian chạy",
        "memory_metric": "Bộ nhớ",
        "node_expansion_subtitle": "Node đang được thuật toán chọn để mở rộng",
        "frontier_subtitle": "Các trạng thái ứng viên đang chờ trong Frontier",
        "reached_subtitle": "Các trạng thái đã phát hiện, giới hạn để dễ nhìn",
        "selection_key": "Khóa chọn",
        "game_title": "Chơi trực quan",
        "game_note": "Bấm trực tiếp vào ô cạnh ô trống để di chuyển. Ô bị mờ là ô chưa đi được.",
        "game_moves": "số bước",
        "game_solved": "Đã về đích",
        "game_progress": "Đang chơi",
        "slide_tile": "Vuốt {tile}",
        "cannot_move": "Không thể đi {action}",
        "not_adjacent": "Ô này không nằm cạnh ô trống.",
        "reset_game": "Đặt lại ván chơi",
        "use_as_start": "Dùng làm trạng thái bắt đầu",
        "move_up": "Lên",
        "move_down": "Xuống",
        "move_left": "Trái",
        "move_right": "Phải",
        "undo": "Hoàn tác",
        "tree_start": "BẮT ĐẦU",
        "tree_goal": "ĐÍCH",
        "tree_depth": "độ sâu {depth}",
        "tree_parent": "cha",
        "tree_action": "hành động",
        "choose_action_hint": "Chọn thuật toán, bấm Chạy thuật toán đã chọn, rồi mở tab Trace học thuật để xem Node / Frontier / Reached.",
        "trace_run_title": "Cách chạy Node / Frontier / Reached",
        "trace_run_steps": "1. Xem cách chạy bằng bảng Node / Frontier / Reached. 2. Xem cách chạy bằng sơ đồ cây tìm kiếm. Chọn nhóm thuật toán, bấm Chạy thuật toán đã chọn, rồi mở tab Trace học thuật để xem cả hai.",
        "trace_result_hint": "Kết quả đã tạo xong. Mở tab Trace học thuật bên dưới để xem Node / Frontier / Reached theo từng bước mở rộng.",
        "image_game_title": "Trò chơi từ ảnh",
        "image_game_note": "Tải một ảnh lên để biến thành bộ xếp hình 8-puzzle. App dùng ảnh làm nền cho 8 ô, ô 0 là ô trống.",
        "image_upload": "Tải ảnh làm đề trò chơi",
        "image_mode_on": "Đang dùng ảnh làm puzzle",
        "image_mode_off": "Đang dùng số thường",
        "clear_image": "Bỏ ảnh",
        "image_ready": "Ảnh đã sẵn sàng. Hãy bấm các ô cạnh ô trống để chơi.",
        "feature_mode": "Tính năng",
        "feature_puzzle": "8-Puzzle Search",
        "feature_image_puzzle": "Trò chơi xếp hình từ ảnh",
        "feature_thu_duc": "Tô màu đồ thị Thủ Đức",
        "image_controls": "Ảnh trò chơi",
        "click_tile_hint": "Bấm trực tiếp vào ô cạnh ô trống để di chuyển. Không cần dùng nút điều hướng riêng.",
        "thu_duc_title": "Tô màu đồ thị Thủ Đức",
        "thu_duc_subtitle": "Demo CSP graph coloring: mỗi phường là một biến, miền là màu, cạnh giáp ranh là ràng buộc khác màu.",
        "thu_duc_palette": "Số màu tối đa",
        "thu_duc_stats": "Thống kê graph coloring",
        "thu_duc_assignments": "Bảng tô màu từng phường",
        "thu_duc_steps": "Các bước tô màu",
        "thu_duc_valid": "Hợp lệ",
        "thu_duc_invalid": "Có xung đột",
        "thu_duc_csp_hint": "Chọn nhóm Constraint Satisfaction Problems và thuật toán Constraint Graph để mở demo tô màu đồ thị Thủ Đức.",
        "thu_duc_color_teal": "Xanh ngọc",
        "thu_duc_color_amber": "Vàng đất",
        "thu_duc_color_brick": "Đỏ gạch",
        "thu_duc_color_violet": "Tím than",
        "thu_duc_color_sky": "Xanh trời",
        "thu_duc_color_lotus": "Hồng sen",
        "thu_duc_stat_regions": "Số vùng",
        "thu_duc_stat_edges": "Số cạnh",
        "thu_duc_stat_colors_used": "Số màu dùng",
        "thu_duc_stat_status": "Trạng thái",
        "thu_duc_no_conflicts": "Không có hai vùng giáp ranh nào trùng màu.",
        "heuristic_note_uninformed": "Thuật toán này không dùng h(n) để chọn node; h(n) chỉ dùng cho bảng giải thích/certificate.",
        "heuristic_note_informed": "Thuật toán này dùng h(n) trực tiếp trong priority hoặc đánh giá trạng thái.",
        "heuristic_note_csp": "CSP ưu tiên biến/ràng buộc; h(n) chỉ hỗ trợ đo trạng thái/xung đột trong demo.",
        "heuristic_note_adversarial": "Nhóm này dùng utility/expected value trên Caro; h(n) của 8-puzzle chỉ còn để giữ giao diện chung.",
        "heuristic_note_complex": "Mô hình môi trường mở rộng có thể dùng h(n) như ước lượng chất lượng, không phải priority chuẩn của solver 8-puzzle.",
        "generate_pack": "Tạo gói nộp bài",
        "download_docx": "Tải DOCX",
        "download_pdf": "Tải PDF",
        "download_html": "Tải HTML",
        "download_csv": "Tải Benchmark CSV",
        "manual_start_input": "Nhập Start thủ công",
    },
    "en": {
        "page_title": "8-Puzzle Search Lab",
        "page_subtitle": "Visualize BFS, UCS, A*, IDA*, and local search algorithms on the same board.",
        "advanced_settings": "Advanced settings",
        "result_details": "Detailed result table",
        "summary_tab": "Summary",
        "academic_trace_tab": "Trace",
        "heuristics_tab": "Heuristics",
        "experiment_tab": "Experiment",
        "path_player_tab": "Path Player",
        "report_tab": "Report",
        "controls": "Controls",
        "language": "Language / Ngôn ngữ",
        "algorithm": "Algorithm",
        "algorithm_group": "Algorithm group",
        "heuristic": "Heuristic",
        "seed": "Seed",
        "scramble_moves": "Random scramble moves",
        "shuffle": "Shuffle matrix",
        "max_expansions": "Max expansions",
        "max_trace_rows": "Max trace rows",
        "frontier_preview": "Frontier preview",
        "reached_preview": "Reached preview",
        "ids_depth": "IDS max depth",
        "ida_iterations": "IDA* iterations",
        "local_steps": "Local max steps",
        "random_restarts": "Random restarts",
        "beam_width": "Beam width",
        "board_panel": "8-puzzle matrix",
        "initial_shuffle": "The current start state was shuffled 20 moves from Goal.",
        "shuffle_note": "Shuffled the matrix {moves} moves from Goal (seed={seed}, run {count}).",
        "demo_preset": "Demo preset",
        "load_preset": "Use preset",
        "preset_note": "Using demo preset: {name}.",
        "start_state": "Start state",
        "goal_state": "Goal state",
        "goal_caption": "Fixed target: move blank tile 0 to the bottom-right corner.",
        "goal_and_input": "Goal and custom input",
        "custom_start": "Custom start state",
        "custom_help": "Enter 9 numbers from 0 to 8, for example: 1 2 3 4 5 6 0 7 8",
        "use_custom": "Use custom state",
        "run": "Run",
        "run_selected": "Run selected algorithm",
        "compare_all": "Compare selected group",
        "notes": puzzle.comparison_notes(),
        "choose_action": "Choose an action from the run panel.",
        "run_summary": "Run summary",
        "final_state": "Final state",
        "best_final_state": "Best / current final state",
        "solution_path": "Solution path",
        "step": "Step",
        "start": "Start",
        "trace": "Node / Frontier / Reached trace",
        "algorithm_certificate": "Algorithm Certificate",
        "certificate_status": "Certificate status",
        "certificate_pass": "PASS",
        "certificate_fail": "FAIL",
        "heuristic_inspector": "Heuristic Inspector",
        "heuristic_totals": "Heuristic totals",
        "tile_contributions": "Tile contributions",
        "linear_conflicts": "Linear Conflict pairs",
        "no_linear_conflicts": "No Linear Conflict pairs in this state.",
        "trace_story": "Why This Node?",
        "experiment_lab": "Experiment Lab",
        "run_experiment": "Run Experiment Lab",
        "download_experiment": "Download experiment report",
        "path_playback": "Path playback",
        "coursework_report": "Coursework report",
        "download_report": "Download Markdown report",
        "report_preview": "Report content",
        "benchmark": "Small demo benchmark",
        "run_benchmark": "Run preset benchmark",
        "benchmark_caption": "Benchmark uses fixed presets and disables trace for quick report-ready measurements.",
        "comparison": "Algorithm comparison",
        "academic_panel": "Academic foundation",
        "grading_checklist": "Submission checklist",
        "heuristic_usage": "How h(n) is used",
        "demo_readiness": "Demo readiness",
        "run_mode": "Run mode",
        "solvable": "Solvable",
        "unsolvable": "Unsolvable",
        "current_preset": "Current preset",
        "selected_heuristic": "h(n)",
        "trace_player": "Academic Trace Player",
        "trace_replay_row": "Trace row to inspect",
        "selected_node": "Selected node",
        "frontier_after": "Frontier after expansion",
        "reached_after": "Reached after expansion",
        "generated_skipped": "Generated / Skipped",
        "search_tree_preview": "Search Tree Preview",
        "peas_model": "PEAS",
        "problem_variant": "Problem formulation by algorithm",
        "problem_definition": "Problem model",
        "algorithm_profile": "Selected algorithm profile",
        "evaluation_criteria": "Evaluation criteria",
        "trace_glossary": "Meaning of Node / Frontier / Reached",
        "objective": "Objective",
        "state_space": "State space",
        "transition_model": "Transition model",
        "heuristic_formula": "Heuristic formula",
        "priority_basis": "Priority basis: g(n), h(n), f(n)",
        "primary_basis": "Primary basis",
        "priority_rule": "Priority rule",
        "uses_component": "Used?",
        "component_meaning": "Meaning in the selected algorithm",
        "yes": "Yes",
        "no": "No",
        "implicit": "Implicit",
        "path_player": "Step-by-step path viewer",
        "previous_step": "Previous step",
        "next_step": "Next step",
        "step_slider": "Select step to inspect",
        "before_move": "State before the move",
        "after_move": "Current state",
        "current_action": "Action just applied",
        "next_action": "Next action",
        "route_sequence": "Action sequence",
        "route_table": "Full route table",
        "no_solution_path": "The algorithm has not found a route to the Goal, so there are no steps to replay.",
        "total_steps": "Total steps",
        "sa_initial_temp": "SA initial temperature",
        "sa_cooling_rate": "SA cooling rate",
        "sa_min_temp": "SA minimum temperature",
        "sa_max_steps": "SA max steps",
        "app_kicker": "AI Search Visualizer",
        "state_lab": "state lab",
        "algorithm_cockpit": "algorithm cockpit",
        "random_manual": "Random/manual",
        "path_length": "Path length",
        "expanded_metric": "Expanded",
        "generated_metric": "Generated",
        "runtime_metric": "Runtime",
        "memory_metric": "Memory",
        "node_expansion_subtitle": "Node currently selected for expansion",
        "frontier_subtitle": "Next candidate states waiting in the frontier",
        "reached_subtitle": "States discovered so far, capped for readability",
        "selection_key": "Selection Key",
        "game_title": "Interactive play",
        "game_note": "Click a tile next to the blank to move it. Disabled tiles are not legal moves.",
        "game_moves": "moves",
        "game_solved": "Goal reached",
        "game_progress": "In progress",
        "slide_tile": "Slide {tile}",
        "cannot_move": "Cannot move {action}",
        "not_adjacent": "That tile is not next to the blank.",
        "reset_game": "Reset game",
        "use_as_start": "Use as Start",
        "move_up": "Up",
        "move_down": "Down",
        "move_left": "Left",
        "move_right": "Right",
        "undo": "Undo",
        "tree_start": "START",
        "tree_goal": "GOAL",
        "tree_depth": "depth {depth}",
        "tree_parent": "parent",
        "tree_action": "action",
        "choose_action_hint": "Choose an algorithm, press Run selected algorithm, then open the Trace tab to inspect Node / Frontier / Reached.",
        "trace_run_title": "How to run Node / Frontier / Reached",
        "trace_run_steps": "1. View the run as a Node / Frontier / Reached table. 2. View the run as a search-tree diagram. Choose the algorithm group, press Run selected algorithm, then open the Trace tab to inspect both.",
        "trace_result_hint": "The run is ready. Open the Trace tab below to inspect Node / Frontier / Reached for each expansion step.",
        "image_game_title": "Image puzzle game",
        "image_game_note": "Upload an image to turn it into an 8-puzzle. The app uses the image as the tile texture and keeps tile 0 blank.",
        "image_upload": "Upload puzzle image",
        "image_mode_on": "Image puzzle enabled",
        "image_mode_off": "Number puzzle enabled",
        "clear_image": "Clear image",
        "image_ready": "Image is ready. Click tiles next to the blank to play.",
        "feature_mode": "Feature",
        "feature_puzzle": "8-Puzzle Search",
        "feature_image_puzzle": "Image puzzle game",
        "feature_thu_duc": "Thu Duc Graph Coloring",
        "image_controls": "Puzzle image",
        "click_tile_hint": "Click a tile next to the blank to move it. No separate D-pad is needed.",
        "thu_duc_title": "Thu Duc graph coloring",
        "thu_duc_subtitle": "CSP graph coloring demo: each ward is a variable, colors are domains, adjacency edges require different colors.",
        "thu_duc_palette": "Maximum colors",
        "thu_duc_stats": "Graph coloring statistics",
        "thu_duc_assignments": "Ward color assignments",
        "thu_duc_steps": "Coloring steps",
        "thu_duc_valid": "Valid",
        "thu_duc_invalid": "Conflicts found",
        "thu_duc_csp_hint": "Choose Constraint Satisfaction Problems and Constraint Graph to open the Thu Duc graph coloring demo.",
        "thu_duc_color_teal": "Teal",
        "thu_duc_color_amber": "Amber",
        "thu_duc_color_brick": "Brick Red",
        "thu_duc_color_violet": "Deep Violet",
        "thu_duc_color_sky": "Sky Blue",
        "thu_duc_color_lotus": "Lotus Pink",
        "thu_duc_stat_regions": "Regions",
        "thu_duc_stat_edges": "Edges",
        "thu_duc_stat_colors_used": "Colors used",
        "thu_duc_stat_status": "Status",
        "thu_duc_no_conflicts": "No adjacent regions share a color.",
        "heuristic_note_uninformed": "This algorithm does not use h(n) for node selection; h(n) is shown only for explanation/certification.",
        "heuristic_note_informed": "This algorithm directly uses h(n) in priority or state evaluation.",
        "heuristic_note_csp": "CSP focuses on variables/constraints; h(n) only supports state/conflict scoring in the demo.",
        "heuristic_note_adversarial": "This group uses utility/expected value on Caro; 8-puzzle h(n) is kept only for the shared UI.",
        "heuristic_note_complex": "The extended-environment model may use h(n) as a quality estimate, not as a standard 8-puzzle solver priority.",
        "generate_pack": "Generate Submission Pack",
        "download_docx": "Download DOCX",
        "download_pdf": "Download PDF",
        "download_html": "Download HTML",
        "download_csv": "Download Benchmark CSV",
        "manual_start_input": "Manual Start input",
    },
}

HELP: Dict[str, Dict[str, str]] = {
    "vi": {
        "language": "Đổi toàn bộ nhãn và giải thích trong app giữa Tiếng Việt và English.",
        "algorithm": "Chọn thuật toán tìm kiếm để chạy trên cùng trạng thái Start hiện tại.",
        "heuristic": "Chọn hàm h(n): Misplaced Tiles (số ô sai vị trí) hoặc Manhattan Distance (tổng khoảng cách từng ô).",
        "seed": "Seed nền cho thao tác trộn. Khi bấm chạy, app tự sinh seed mới để đường duyệt/tie-break có tính ngẫu nhiên.",
        "scramble_moves": "Số bước đi ngẫu nhiên từ Goal để tạo Start. Số lớn hơn thường làm bài khó hơn.",
        "shuffle": "Tạo Start mới bằng cách đi ngẫu nhiên từ Goal, nên trạng thái luôn solvable.",
        "max_expansions": "Giới hạn số node được mở rộng để tránh thuật toán chạy quá lâu hoặc treo app.",
        "max_trace_rows": "Giới hạn số dòng bảng Node / Frontier / Reached hiển thị trong app.",
        "frontier_preview": "Số trạng thái frontier được xem trước trong mỗi dòng trace.",
        "reached_preview": "Số trạng thái reached được xem trước trong mỗi dòng trace.",
        "ids_depth": "Độ sâu tối đa cho IDS. Nếu nghiệm sâu hơn giới hạn này, IDS có thể không tìm thấy.",
        "ida_iterations": "Số lần tăng threshold tối đa của IDA*.",
        "local_steps": "Giới hạn số bước cho các thuật toán tìm kiếm cục bộ như hill climbing và beam search.",
        "random_restarts": "Số lần khởi động lại của Random-Restart Hill Climbing để giảm kẹt local optimum.",
        "beam_width": "Số trạng thái tốt nhất được giữ lại ở mỗi vòng của Local Beam Search.",
        "custom_start": "Nhập 9 số từ 0 đến 8. Ví dụ: 1 2 3 4 5 6 0 7 8.",
        "use_custom": "Áp dụng ma trận bạn nhập làm Start state hiện tại.",
        "run_selected": "Chạy thuật toán đang chọn với seed mới, rồi hiển thị lời giải, trace, g(n), h(n), f(n).",
        "compare_all": "Chạy các thuật toán trong nhóm đang chọn với seed mới trên cùng Start để so sánh Expanded, Generated, Runtime và Optimal.",
        "previous_step": "Lùi lại một bước trong đường đi lời giải.",
        "next_step": "Tiến tới một bước trong đường đi lời giải.",
        "step_slider": "Kéo để nhảy tới bước bất kỳ trong lời giải.",
        "metric_step": "Chỉ số bước hiện tại trên tổng số bước của lời giải.",
        "metric_g": "g(n): chi phí thật từ Start đến trạng thái hiện tại, ở đây bằng số bước đã đi.",
        "metric_h": "h(n): heuristic ước lượng số bước còn lại từ trạng thái hiện tại đến Goal.",
        "metric_f": "f(n)=g(n)+h(n), dùng làm priority trong A* và threshold trong IDA*.",
        "metric_total_steps": "Tổng số hành động trong đường đi lời giải tìm được.",
        "board_tile": "Ô {value} tại hàng {row}, cột {col}.",
        "blank_tile": "Ô trống 0 tại hàng {row}, cột {col}; đây là ô được di chuyển trong 8-Puzzle.",
        "start_board": "Ma trận ban đầu mà thuật toán cần biến đổi thành Goal.",
        "goal_board": "Ma trận đích cố định. Thuật toán thành công khi Start biến thành ma trận này.",
        "sa_initial_temp": "Nhiệt độ ban đầu cao cho phép chấp nhận nhiều bước đi xấu hơn ban đầu.",
        "sa_cooling_rate": "Tỷ lệ giảm nhiệt độ mỗi bước. Gần 1 = làm nguội chậm, khám phá nhiều hơn.",
        "sa_min_temp": "Dừng khi nhiệt độ xuống dưới giá trị này.",
        "sa_max_steps": "Giới hạn số bước để tránh chạy vô hạn.",
    },
    "en": {
        "language": "Switch all labels and explanations between Vietnamese and English.",
        "algorithm": "Choose the search algorithm to run on the current Start state.",
        "heuristic": "Choose h(n): Misplaced Tiles (number of wrong tiles) or Manhattan Distance (sum of tile grid distances).",
        "seed": "Base seed for shuffling. Each Run click gets a fresh seed so traversal/tie-breaks can vary.",
        "scramble_moves": "Number of random legal moves from Goal used to create Start. Larger values are usually harder.",
        "shuffle": "Creates a new Start by walking randomly from Goal, so the state is always solvable.",
        "max_expansions": "Limits expanded nodes to prevent very long runs or UI hangs.",
        "max_trace_rows": "Limits rows shown in the Node / Frontier / Reached trace table.",
        "frontier_preview": "Number of frontier states previewed in each trace row.",
        "reached_preview": "Number of reached states previewed in each trace row.",
        "ids_depth": "Maximum depth for IDS. If the solution is deeper, IDS may not find it.",
        "ida_iterations": "Maximum number of threshold increases for IDA*.",
        "local_steps": "Step limit for local search algorithms such as hill climbing and beam search.",
        "random_restarts": "Number of restarts for Random-Restart Hill Climbing to reduce local optimum risk.",
        "beam_width": "Number of best states retained at each Local Beam Search iteration.",
        "custom_start": "Enter 9 numbers from 0 to 8. Example: 1 2 3 4 5 6 0 7 8.",
        "use_custom": "Apply the entered matrix as the current Start state.",
        "run_selected": "Run the selected algorithm with a fresh seed and show solution path, trace, g(n), h(n), f(n).",
        "compare_all": "Run algorithms in the selected group with a fresh seed on the same Start to compare Expanded, Generated, Runtime, and Optimality.",
        "previous_step": "Move one step backward in the solution path.",
        "next_step": "Move one step forward in the solution path.",
        "step_slider": "Drag to jump to any solution step.",
        "metric_step": "Current step index over total solution steps.",
        "metric_g": "g(n): actual path cost from Start to the current state; here it equals moves made.",
        "metric_h": "h(n): heuristic estimate of remaining moves from the current state to Goal.",
        "metric_f": "f(n)=g(n)+h(n), used as priority in A* and threshold in IDA*.",
        "metric_total_steps": "Total number of actions in the found solution path.",
        "board_tile": "Tile {value} at row {row}, column {col}.",
        "blank_tile": "Blank tile 0 at row {row}, column {col}; this is the movable 8-Puzzle tile.",
        "start_board": "Initial matrix that the algorithm must transform into Goal.",
        "goal_board": "Fixed target matrix. The algorithm succeeds when Start becomes this matrix.",
        "sa_initial_temp": "High initial temperature allows accepting more bad moves early.",
        "sa_cooling_rate": "Temperature decay per step. Closer to 1 = slower cooling, more exploration.",
        "sa_min_temp": "Stop when temperature drops below this threshold.",
        "sa_max_steps": "Maximum iterations to prevent infinite runs.",
    },
}

TABLE_COLUMNS: Dict[str, Dict[str, str]] = {
    "vi": {
        "Group": "Nhóm",
        "Algorithm": "Thuật toán",
        "Found": "Tìm thấy",
        "Path Length": "Độ dài đường đi",
        "Expanded": "Node đã mở rộng",
        "Generated": "Node đã sinh",
        "Max Frontier": "Frontier lớn nhất",
        "Reached": "Reached",
        "Runtime ms": "Thời gian ms",
        "Optimal": "Tối ưu",
        "Complete": "Đầy đủ",
        "Memory": "Bộ nhớ",
        "Message": "Ghi chú",
        "Path Cost": "Chi phí đường đi",
        "Optimal Gap": "Độ lệch tối ưu",
        "Metric": "Chỉ số",
        "Baseline Cost": "Chi phí chuẩn",
        "Step": "Bước",
        "Action": "Hành động",
        "Depth": "Độ sâu",
        "Priority Rule": "Quy tắc ưu tiên",
        "Selection Key": "Khóa chọn node",
        "Generated Children": "Child sinh ra",
        "Skipped States": "State bỏ qua",
        "Decision/Note": "Quyết định / Ghi chú",
        "State": "Trạng thái",
        "Check": "Kiểm chứng",
        "Value": "Giá trị",
        "Preset": "Preset",
        "Component": "Thành phần",
        "Criterion": "Tiêu chí",
        "Academic meaning": "Ý nghĩa học thuật",
        "Trace column": "Cột trace",
        "Definition": "Định nghĩa",
        "Tile": "Ô",
        "Current": "Vị trí hiện tại",
        "Goal": "Vị trí đích",
        "Misplaced": "Sai vị trí",
        "Manhattan": "Manhattan",
        "In Goal Row": "Đúng hàng đích",
        "In Goal Column": "Đúng cột đích",
        "Direction": "Hướng",
        "Line": "Dòng/cột",
        "Tile A": "Ô A",
        "Tile B": "Ô B",
        "Current Order": "Thứ tự hiện tại",
        "Goal Order": "Thứ tự ở goal",
        "Penalty": "Phạt",
        "Why This Node": "Vì sao chọn node này",
        "Heuristic": "Heuristic",
        "Family": "Nhóm",
        "Selection rule": "Quy tắc chọn node",
        "Evaluation function": "Hàm đánh giá",
        "Guarantee": "Đảm bảo",
        "Main limitation": "Hạn chế chính",
        "Item": "Mục",
        "Status": "Trạng thái",
        "Evidence": "Minh chứng",
        "Why it matters": "Ý nghĩa học thuật",
    },
    "en": {},
}

ACTION_LABELS: Dict[str, Dict[str, str]] = {
    "vi": {
        "Start": "Bắt đầu",
        "Up": "Lên",
        "Down": "Xuống",
        "Left": "Trái",
        "Right": "Phải",
    },
    "en": {},
}

ALGORITHM_PROFILES: Dict[str, Dict[str, Dict[str, str]]] = {
    "vi": {
        "BFS": {
            "Family": "Tìm kiếm mù / không dùng heuristic",
            "Selection rule": "Luôn mở node nông nhất trong hàng đợi FIFO.",
            "Evaluation function": "Không có (Thứ tự FIFO)",
            "Guarantee": "Đầy đủ và tối ưu khi mọi bước có chi phí bằng nhau.",
            "Main limitation": "Tốn bộ nhớ vì phải giữ toàn bộ frontier theo từng tầng.",
            "pseudo": "frontier <- FIFO(start)\nwhile frontier not empty:\n    node <- pop_front(frontier)\n    if node is goal: return solution\n    expand node and append unseen children",
        },
        "DFS": {
            "Family": "Tìm kiếm mù / không dùng heuristic",
            "Selection rule": "Luôn mở node sâu nhất trong stack LIFO.",
            "Evaluation function": "Không có (Thứ tự LIFO stack)",
            "Guarantee": "Không tối ưu; trong app được chặn bởi giới hạn độ sâu/mở rộng.",
            "Main limitation": "Có thể đi sâu vào nhánh kém và bỏ lỡ nghiệm nông.",
            "pseudo": "frontier <- Stack(start)\nwhile frontier not empty:\n    node <- pop(frontier)\n    if node is goal: return solution\n    if depth limit not reached: push children",
        },
        "UCS": {
            "Family": "Tìm kiếm theo chi phí đường đi",
            "Selection rule": "Mở node có g(n) nhỏ nhất trong priority queue.",
            "Evaluation function": "f(n) = g(n)",
            "Guarantee": "Đầy đủ và tối ưu với chi phí không âm; với 8-puzzle c=1 nên gần BFS.",
            "Main limitation": "Không dùng tri thức đích nên có thể mở nhiều node.",
            "pseudo": "frontier <- PriorityQueue(start, priority=g)\nwhile frontier not empty:\n    node <- pop_lowest_g(frontier)\n    if node is goal: return solution\n    relax children by path cost",
        },
        "IDS": {
            "Family": "Tìm kiếm lặp sâu dần",
            "Selection rule": "Chạy Depth-Limited Search với giới hạn 0,1,2,...",
            "Evaluation function": "Không có (Lặp lại DFS giới hạn độ sâu)",
            "Guarantee": "Tối ưu theo số bước nếu giới hạn đủ lớn và chi phí bước bằng nhau.",
            "Main limitation": "Lặp lại việc mở node ở các tầng nông.",
            "pseudo": "for limit in 0..L:\n    result <- depth_limited_search(start, limit)\n    if result found: return result",
        },
        "Greedy": {
            "Family": "Tìm kiếm có thông tin",
            "Selection rule": "Mở node có h(n) nhỏ nhất.",
            "Evaluation function": "f(n) = h(n)",
            "Guarantee": "Không đảm bảo tối ưu.",
            "Main limitation": "Dễ bị heuristic dẫn vào đường ngắn hạn nhưng không tốt toàn cục.",
            "pseudo": "frontier <- PriorityQueue(start, priority=h)\nwhile frontier not empty:\n    node <- pop_lowest_h(frontier)\n    if node is goal: return solution\n    expand and rank children by h",
        },
        "A*": {
            "Family": "Tìm kiếm có thông tin, tối ưu theo heuristic admissible",
            "Selection rule": "Mở node có g(n)+h(n) nhỏ nhất.",
            "Evaluation function": "f(n) = g(n) + h(n)",
            "Guarantee": "Tối ưu nếu h admissible; Manhattan admissible cho 8-puzzle.",
            "Main limitation": "Có thể tốn bộ nhớ vì vẫn giữ frontier và best-g.",
            "pseudo": "frontier <- PriorityQueue(start, priority=g+h)\nwhile frontier not empty:\n    node <- pop_lowest_f(frontier)\n    if node is goal: return solution\n    relax children if a lower g is found",
        },
        "IDA*": {
            "Family": "A* lặp sâu theo ngưỡng f",
            "Selection rule": "DFS nhưng cắt nhánh khi f(n) vượt threshold.",
            "Evaluation function": "f(n) = g(n) + h(n), threshold tăng dần",
            "Guarantee": "Tối ưu với heuristic admissible nếu không bị giới hạn vòng lặp.",
            "Main limitation": "Có thể mở lại node nhiều lần qua các ngưỡng.",
            "pseudo": "threshold <- h(start)\nrepeat:\n    run DFS bounded by f <= threshold\n    if goal found: return solution\n    threshold <- smallest f that exceeded threshold",
        },
        "Simple Hill Climbing": {
            "Family": "Tìm kiếm cục bộ",
            "Selection rule": "Chọn láng giềng cải thiện đầu tiên.",
            "Evaluation function": "minimize h(n)",
            "Guarantee": "Không đầy đủ, không tối ưu.",
            "Main limitation": "Dễ kẹt local optimum hoặc plateau.",
            "pseudo": "current <- start\nwhile improvement exists:\n    move to first neighbor with lower h\nreturn current",
        },
        "Steepest-Ascent Hill Climbing": {
            "Family": "Tìm kiếm cục bộ",
            "Selection rule": "Chọn láng giềng có h(n) nhỏ nhất trong toàn bộ neighbors.",
            "Evaluation function": "minimize h(n)",
            "Guarantee": "Không đầy đủ, không tối ưu.",
            "Main limitation": "Vẫn kẹt local optimum dù xét toàn bộ láng giềng.",
            "pseudo": "current <- start\nwhile best neighbor has lower h:\n    current <- best neighbor\nreturn current",
        },
        "Stochastic Hill Climbing": {
            "Family": "Tìm kiếm cục bộ ngẫu nhiên",
            "Selection rule": "Chọn ngẫu nhiên một láng giềng có cải thiện.",
            "Evaluation function": "minimize h(n)",
            "Guarantee": "Không đầy đủ, không tối ưu.",
            "Main limitation": "Kết quả phụ thuộc seed và vẫn có thể kẹt.",
            "pseudo": "current <- start\nwhile improving neighbors exist:\n    current <- random improving neighbor\nreturn current",
        },
        "Random-Restart Hill Climbing": {
            "Family": "Tìm kiếm cục bộ với khởi động lại",
            "Selection rule": "Chạy hill climbing nhiều lần từ các trạng thái random-walk xuất phát từ start.",
            "Evaluation function": "minimize h(n)",
            "Guarantee": "Tăng xác suất tìm nghiệm nhưng không đảm bảo tối ưu.",
            "Main limitation": "Cần nhiều restart nếu landscape khó.",
            "pseudo": "best <- start\nfor each restart:\n    run hill climbing\n    keep best state found\nreturn goal if any run reaches it",
        },
        "Local Beam Search": {
            "Family": "Tìm kiếm cục bộ theo chùm trạng thái",
            "Selection rule": "Giữ k trạng thái tốt nhất theo h(n) ở mỗi vòng.",
            "Evaluation function": "minimize h(n) over beam",
            "Guarantee": "Không đầy đủ, không tối ưu.",
            "Main limitation": "Beam hẹp dễ mất nhánh tốt; beam rộng tốn tính toán hơn.",
            "pseudo": "beam <- {start}\nwhile step limit not reached:\n    generate successors of every beam state\n    beam <- k best successors by h\n    if goal in beam: return solution",
        },
        "Simulated Annealing": {
            "Family": "Tìm kiếm cục bộ ngẫu nhiên với giảm nhiệt độ",
            "Selection rule": "Chấp nhận láng giềng tốt ngay; láng giềng xấu với xác suất e^(-Δh/T).",
            "Evaluation function": "minimize h(n) với xác suất chấp nhận giảm theo nhiệt độ",
            "Guarantee": "Không đảm bảo tối ưu, nhưng xác suất tìm nghiệm tăng theo thời gian.",
            "Main limitation": "Cần điều chỉnh T₀, cooling rate, min_T phù hợp với bài toán.",
            "pseudo": "current <- start, T <- T₀\nwhile T > T_min:\n    neighbor <- random(successors(current))\n    Δh <- h(neighbor) - h(current)\n    if Δh < 0 or random() < exp(-Δh/T):\n        current <- neighbor\n    T <- T × cooling_rate\nreturn best found",
        },
    },
    "en": {},
}

ALGORITHM_PROFILES["en"] = {
    "BFS": {
        "Family": "Uninformed search",
        "Selection rule": "Always expands the shallowest node from a FIFO queue.",
        "Evaluation function": "None (FIFO order)",
        "Guarantee": "Complete and optimal when every step has equal cost.",
        "Main limitation": "High memory use because it stores the frontier layer by layer.",
        "pseudo": "frontier <- FIFO(start)\nwhile frontier not empty:\n    node <- pop_front(frontier)\n    if node is goal: return solution\n    expand node and append unseen children",
    },
    "DFS": {
        "Family": "Uninformed search",
        "Selection rule": "Always expands the deepest node from a LIFO stack.",
        "Evaluation function": "None (LIFO stack order)",
        "Guarantee": "Not optimal; bounded here by depth and expansion limits.",
        "Main limitation": "Can follow poor deep branches before shallow solutions.",
        "pseudo": "frontier <- Stack(start)\nwhile frontier not empty:\n    node <- pop(frontier)\n    if node is goal: return solution\n    if depth limit not reached: push children",
    },
    "UCS": {
        "Family": "Path-cost search",
        "Selection rule": "Expands the node with minimum g(n).",
        "Evaluation function": "f(n) = g(n)",
        "Guarantee": "Complete and optimal for non-negative costs; with 8-puzzle c=1 it resembles BFS.",
        "Main limitation": "Does not use goal-directed heuristic knowledge.",
        "pseudo": "frontier <- PriorityQueue(start, priority=g)\nwhile frontier not empty:\n    node <- pop_lowest_g(frontier)\n    if node is goal: return solution\n    relax children by path cost",
    },
    "IDS": {
        "Family": "Iterative deepening search",
        "Selection rule": "Runs depth-limited search with limits 0,1,2,...",
        "Evaluation function": "None (depth-limited DFS iterations)",
        "Guarantee": "Optimal in number of moves when the limit is sufficient and step costs are equal.",
        "Main limitation": "Re-expands shallow nodes across iterations.",
        "pseudo": "for limit in 0..L:\n    result <- depth_limited_search(start, limit)\n    if result found: return result",
    },
    "Greedy": {
        "Family": "Informed search",
        "Selection rule": "Expands the node with minimum h(n).",
        "Evaluation function": "f(n) = h(n)",
        "Guarantee": "Not optimal.",
        "Main limitation": "Can be misled by short-term heuristic progress.",
        "pseudo": "frontier <- PriorityQueue(start, priority=h)\nwhile frontier not empty:\n    node <- pop_lowest_h(frontier)\n    if node is goal: return solution\n    expand and rank children by h",
    },
    "A*": {
        "Family": "Informed optimal search with admissible heuristic",
        "Selection rule": "Expands the node with minimum g(n)+h(n).",
        "Evaluation function": "f(n) = g(n) + h(n)",
        "Guarantee": "Optimal when h is admissible; Manhattan is admissible for 8-puzzle.",
        "Main limitation": "Can consume substantial memory for frontier and best-g records.",
        "pseudo": "frontier <- PriorityQueue(start, priority=g+h)\nwhile frontier not empty:\n    node <- pop_lowest_f(frontier)\n    if node is goal: return solution\n    relax children if a lower g is found",
    },
    "IDA*": {
        "Family": "A* with iterative f-threshold deepening",
        "Selection rule": "DFS pruned by an increasing f-threshold.",
        "Evaluation function": "f(n) = g(n) + h(n), increasing threshold",
        "Guarantee": "Optimal with admissible h if not stopped by iteration limits.",
        "Main limitation": "Can re-expand nodes across thresholds.",
        "pseudo": "threshold <- h(start)\nrepeat:\n    run DFS bounded by f <= threshold\n    if goal found: return solution\n    threshold <- smallest f that exceeded threshold",
    },
    "Simple Hill Climbing": {
        "Family": "Local search",
        "Selection rule": "Moves to the first improving neighbor.",
        "Evaluation function": "minimize h(n)",
        "Guarantee": "Not complete and not optimal.",
        "Main limitation": "Can stop at local optima or plateaus.",
        "pseudo": "current <- start\nwhile improvement exists:\n    move to first neighbor with lower h\nreturn current",
    },
    "Steepest-Ascent Hill Climbing": {
        "Family": "Local search",
        "Selection rule": "Moves to the best neighbor among all neighbors.",
        "Evaluation function": "minimize h(n)",
        "Guarantee": "Not complete and not optimal.",
        "Main limitation": "Still vulnerable to local optima.",
        "pseudo": "current <- start\nwhile best neighbor has lower h:\n    current <- best neighbor\nreturn current",
    },
    "Stochastic Hill Climbing": {
        "Family": "Randomized local search",
        "Selection rule": "Randomly selects an improving neighbor.",
        "Evaluation function": "minimize h(n)",
        "Guarantee": "Not complete and not optimal.",
        "Main limitation": "Seed-dependent and can still get stuck.",
        "pseudo": "current <- start\nwhile improving neighbors exist:\n    current <- random improving neighbor\nreturn current",
    },
    "Random-Restart Hill Climbing": {
        "Family": "Local search with restarts",
        "Selection rule": "Runs hill climbing from several random-walk descendants of start.",
        "Evaluation function": "minimize h(n)",
        "Guarantee": "Improves success probability but does not guarantee optimality.",
        "Main limitation": "Needs many restarts on difficult landscapes.",
        "pseudo": "best <- start\nfor each restart:\n    run hill climbing\n    keep best state found\nreturn goal if any run reaches it",
    },
    "Local Beam Search": {
        "Family": "Population-based local search",
        "Selection rule": "Keeps the k best states by h(n) at each iteration.",
        "Evaluation function": "minimize h(n) over beam",
        "Guarantee": "Not complete and not optimal.",
        "Main limitation": "Narrow beams can discard useful branches; wide beams cost more.",
        "pseudo": "beam <- {start}\nwhile step limit not reached:\n    generate successors of every beam state\n    beam <- k best successors by h\n    if goal in beam: return solution",
    },
    "Simulated Annealing": {
        "Family": "Stochastic local search with temperature schedule",
        "Selection rule": "Accept better neighbors immediately; worse neighbors with probability e^(-Δh/T).",
        "Evaluation function": "minimize h(n) with temperature-dependent acceptance",
        "Guarantee": "Not optimal, but probability of finding solution increases with time.",
        "Main limitation": "Requires tuning T₀, cooling rate, and min_T for the problem.",
        "pseudo": "current <- start, T <- T₀\nwhile T > T_min:\n    neighbor <- random(successors(current))\n    Δh <- h(neighbor) - h(current)\n    if Δh < 0 or random() < exp(-Δh/T):\n        current <- neighbor\n    T <- T × cooling_rate\nreturn best found",
    },
}

ALGORITHM_BASIS: Dict[str, Dict[str, Dict[str, Any]]] = {
    "vi": {
        "BFS": {
            "primary": "Độ sâu / số tầng; tương đương g(n) khi chi phí mỗi bước = 1",
            "rule": "Ưu tiên node nông nhất trước, không dùng heuristic.",
            "g": ("implicit", "Không tính priority bằng g(n), nhưng depth = g(n) vì mỗi bước có cost 1."),
            "h": ("no", "Không dùng ước lượng đến goal."),
            "f": ("no", "Không dùng hàm tổng hợp f(n)."),
        },
        "DFS": {
            "primary": "Thứ tự LIFO / độ sâu nhánh hiện tại",
            "rule": "Ưu tiên node được đưa vào stack gần nhất, không dựa trên chi phí hay heuristic.",
            "g": ("no", "Không chọn node theo chi phí đường đi."),
            "h": ("no", "Không dùng heuristic."),
            "f": ("no", "Không dùng hàm đánh giá f(n)."),
        },
        "UCS": {
            "primary": "g(n)",
            "rule": "Ưu tiên node có chi phí đường đi nhỏ nhất từ start.",
            "g": ("yes", "Thành phần quyết định priority: g(n) càng nhỏ càng được mở trước."),
            "h": ("no", "Không dùng tri thức ước lượng khoảng cách tới goal."),
            "f": ("implicit", "Có thể xem f(n)=g(n) trong UCS."),
        },
        "IDS": {
            "primary": "Độ sâu giới hạn; tương đương kiểm soát g(n) theo từng limit",
            "rule": "Lặp DFS với depth limit tăng dần 0,1,2,...",
            "g": ("implicit", "Depth của node tương ứng số bước đã đi, tức g(n) khi cost=1."),
            "h": ("no", "Không dùng heuristic."),
            "f": ("no", "Không dùng f(n) để xếp priority."),
        },
        "Greedy": {
            "primary": "h(n)",
            "rule": "Ưu tiên node có heuristic nhỏ nhất, tức có vẻ gần goal nhất.",
            "g": ("no", "Không xét chi phí đã đi, nên có thể chọn đường dài."),
            "h": ("yes", "Thành phần quyết định priority: h(n) càng nhỏ càng được mở trước."),
            "f": ("implicit", "Có thể xem f(n)=h(n) trong Greedy."),
        },
        "A*": {
            "primary": "f(n)=g(n)+h(n)",
            "rule": "Cân bằng chi phí đã đi và ước lượng chi phí còn lại.",
            "g": ("yes", "Giữ chi phí thật từ start đến node."),
            "h": ("yes", "Ước lượng chi phí còn lại tới goal."),
            "f": ("yes", "Priority chính: f(n)=g(n)+h(n)."),
        },
        "IDA*": {
            "primary": "f(n)=g(n)+h(n) với ngưỡng tăng dần",
            "rule": "DFS chỉ đi tiếp nếu f(n) không vượt threshold hiện tại.",
            "g": ("yes", "Tính chi phí đã đi trong nhánh DFS hiện tại."),
            "h": ("yes", "Ước lượng chi phí còn lại."),
            "f": ("yes", "Dùng f(n) để cắt nhánh theo threshold."),
        },
        "Simple Hill Climbing": {
            "primary": "h(n)",
            "rule": "Chuyển sang láng giềng đầu tiên có h(n) nhỏ hơn hiện tại.",
            "g": ("no", "Không quan tâm chi phí đường đi đã đi."),
            "h": ("yes", "Dùng h(n) để đánh giá trạng thái tốt hơn."),
            "f": ("no", "Không dùng f(n)=g(n)+h(n)."),
        },
        "Steepest-Ascent Hill Climbing": {
            "primary": "h(n)",
            "rule": "Chọn láng giềng có h(n) nhỏ nhất trong toàn bộ neighbors.",
            "g": ("no", "Không xét chi phí đã đi."),
            "h": ("yes", "Dùng h(n) làm tiêu chí tối ưu cục bộ."),
            "f": ("no", "Không dùng f(n)."),
        },
        "Stochastic Hill Climbing": {
            "primary": "h(n) + chọn ngẫu nhiên trong nhóm cải thiện",
            "rule": "Lọc các neighbor có h(n) tốt hơn rồi chọn ngẫu nhiên một trạng thái.",
            "g": ("no", "Không xét chi phí đường đi."),
            "h": ("yes", "Dùng h(n) để xác định neighbor cải thiện."),
            "f": ("no", "Không dùng f(n)."),
        },
        "Random-Restart Hill Climbing": {
            "primary": "h(n) qua nhiều lần restart",
            "rule": "Mỗi lần restart chạy hill climbing để giảm h(n), rồi giữ kết quả tốt nhất.",
            "g": ("no", "Không ưu tiên node theo path cost."),
            "h": ("yes", "Dùng h(n) để đánh giá tốt/xấu trong từng lần leo đồi."),
            "f": ("no", "Không dùng f(n)."),
        },
        "Local Beam Search": {
            "primary": "h(n) trên tập beam",
            "rule": "Mỗi vòng giữ k trạng thái có h(n) nhỏ nhất.",
            "g": ("no", "Không chọn theo chi phí đã đi."),
            "h": ("yes", "Dùng h(n) để xếp hạng candidates trong beam."),
            "f": ("no", "Không dùng f(n)=g(n)+h(n)."),
        },
        "Simulated Annealing": {
            "primary": "h(n) với xác suất chấp nhận giảm theo T",
            "rule": "Luôn chấp nhận láng giềng tốt hơn; láng giềng xấu hơn với xác suất e^(-Δh/T).",
            "g": ("no", "Không xét chi phí đường đi đã đi."),
            "h": ("yes", "Dùng h(n) để đánh giá độ tốt của trạng thái."),
            "f": ("no", "Không dùng f(n)=g(n)+h(n)."),
        },
    },
    "en": {
        "BFS": {
            "primary": "Depth/level order; equivalent to g(n) when every step cost is 1",
            "rule": "Prioritizes the shallowest node first and does not use a heuristic.",
            "g": ("implicit", "Priority is not computed from g(n), but depth = g(n) because every move costs 1."),
            "h": ("no", "No goal-distance estimate is used."),
            "f": ("no", "No combined evaluation function is used."),
        },
        "DFS": {
            "primary": "LIFO order / current branch depth",
            "rule": "Prioritizes the most recently pushed stack node, not cost or heuristic value.",
            "g": ("no", "Does not choose nodes by path cost."),
            "h": ("no", "Does not use a heuristic."),
            "f": ("no", "Does not use f(n)."),
        },
        "UCS": {
            "primary": "g(n)",
            "rule": "Prioritizes the node with the smallest path cost from start.",
            "g": ("yes", "Main priority component: lower g(n) is expanded first."),
            "h": ("no", "No estimated distance to the goal is used."),
            "f": ("implicit", "UCS can be viewed as f(n)=g(n)."),
        },
        "IDS": {
            "primary": "Depth limit; indirectly controls g(n) at each iteration",
            "rule": "Repeats DFS with increasing depth limits 0,1,2,...",
            "g": ("implicit", "Node depth equals number of moves, so depth = g(n) when cost=1."),
            "h": ("no", "Does not use a heuristic."),
            "f": ("no", "Does not rank nodes by f(n)."),
        },
        "Greedy": {
            "primary": "h(n)",
            "rule": "Prioritizes the node with the smallest heuristic value.",
            "g": ("no", "Ignores accumulated path cost, so it may choose long routes."),
            "h": ("yes", "Main priority component: lower h(n) is expanded first."),
            "f": ("implicit", "Greedy can be viewed as f(n)=h(n)."),
        },
        "A*": {
            "primary": "f(n)=g(n)+h(n)",
            "rule": "Balances actual path cost and estimated remaining cost.",
            "g": ("yes", "Tracks the real cost from start to the node."),
            "h": ("yes", "Estimates the remaining cost to the goal."),
            "f": ("yes", "Main priority: f(n)=g(n)+h(n)."),
        },
        "IDA*": {
            "primary": "f(n)=g(n)+h(n) with increasing threshold",
            "rule": "DFS continues only while f(n) is within the current threshold.",
            "g": ("yes", "Tracks cost along the current DFS branch."),
            "h": ("yes", "Estimates the remaining cost."),
            "f": ("yes", "Uses f(n) to prune nodes by threshold."),
        },
        "Simple Hill Climbing": {
            "primary": "h(n)",
            "rule": "Moves to the first neighbor with lower h(n).",
            "g": ("no", "Does not consider accumulated path cost."),
            "h": ("yes", "Uses h(n) to decide whether a neighbor is better."),
            "f": ("no", "Does not use f(n)=g(n)+h(n)."),
        },
        "Steepest-Ascent Hill Climbing": {
            "primary": "h(n)",
            "rule": "Chooses the neighbor with the lowest h(n) among all neighbors.",
            "g": ("no", "Does not consider path cost."),
            "h": ("yes", "Uses h(n) as the local improvement criterion."),
            "f": ("no", "Does not use f(n)."),
        },
        "Stochastic Hill Climbing": {
            "primary": "h(n) + random choice among improving neighbors",
            "rule": "Filters neighbors with better h(n), then randomly chooses one.",
            "g": ("no", "Does not consider path cost."),
            "h": ("yes", "Uses h(n) to identify improving neighbors."),
            "f": ("no", "Does not use f(n)."),
        },
        "Random-Restart Hill Climbing": {
            "primary": "h(n) across multiple restarts",
            "rule": "Each restart runs hill climbing to reduce h(n), then keeps the best outcome.",
            "g": ("no", "Does not prioritize by path cost."),
            "h": ("yes", "Uses h(n) to judge state quality in each climb."),
            "f": ("no", "Does not use f(n)."),
        },
        "Local Beam Search": {
            "primary": "h(n) across the beam",
            "rule": "Keeps the k states with the smallest h(n) at each iteration.",
            "g": ("no", "Does not select by accumulated path cost."),
            "h": ("yes", "Uses h(n) to rank beam candidates."),
            "f": ("no", "Does not use f(n)=g(n)+h(n)."),
        },
        "Simulated Annealing": {
            "primary": "h(n) with temperature-dependent acceptance",
            "rule": "Always accept better neighbors; worse neighbors with probability e^(-Δh/T).",
            "g": ("no", "Does not consider accumulated path cost."),
            "h": ("yes", "Uses h(n) to evaluate state quality."),
            "f": ("no", "Does not use f(n)=g(n)+h(n)."),
        },
    },
}


def text(lang: str, key: str, **kwargs: Any) -> str:
    value = TEXT.get(lang, {}).get(key, f"[missing:{key}]")
    return value.format(**kwargs) if kwargs else value


def help_text(lang: str, key: str, **kwargs: Any) -> str:
    value = HELP[lang][key]
    return value.format(**kwargs) if kwargs else value


def localize_action(action: str, lang: str) -> str:
    if lang == "en":
        return action
    for english, vietnamese in ACTION_LABELS["vi"].items():
        action = action.replace(english, vietnamese)
    return action


def localize_algorithm_group(group: str, lang: str) -> str:
    if lang == "en":
        return group
    return {
        "Uninformed Search": "Tìm kiếm không dùng heuristic",
        "Informed Search": "Tìm kiếm có heuristic",
        "Local Search": "Tìm kiếm cục bộ",
        "Complex Environments": "Môi trường phức tạp",
        "Complex Environment": "Môi trường phức tạp",
        "Constraint Satisfaction Problems": "Bài toán thỏa mãn ràng buộc",
        "Constraint Satisfaction": "Bài toán thỏa mãn ràng buộc",
        "Adversarial Search": "Tìm kiếm đối kháng",
        "Adversarial / Stochastic Search": "Tìm kiếm đối kháng / xác suất",
    }.get(group, group)


def localize_trace_text(value: Any, lang: str) -> str:
    text_value = str(value or "")
    if lang == "en":
        return text_value
    replacements = {
        "Pop best priority node for A*, expand it, then push improved children.": "Lấy node ưu tiên tốt nhất của A*, mở rộng node đó, rồi đưa các node con tốt hơn vào frontier.",
        "children": "node con",
        "Solver chuẩn": "Bộ giải chuẩn",
        "local search": "tìm kiếm cục bộ",
        "complete/optimal": "đầy đủ/tối ưu",
        "child": "node con",
        "Priority queue ordered by minimum f(n)=g(n)+h(n); ties keep insertion order after h(n).": "Hàng đợi ưu tiên chọn f(n)=g(n)+h(n) nhỏ nhất; nếu hòa thì giữ thứ tự sinh node.",
        "A* selected the node with minimum f(n)=g(n)+h(n); insertion order breaks ties.": "A* chọn node có f(n)=g(n)+h(n) nhỏ nhất; nếu hòa thì dùng thứ tự sinh node.",
        "Selection key": "Khóa chọn",
        "Decision": "Quyết định",
        "Start": "Bắt đầu",
        "Up": "Lên",
        "Down": "Xuống",
        "Left": "Trái",
        "Right": "Phải",
    }
    for english, vietnamese in replacements.items():
        text_value = text_value.replace(english, vietnamese)
    return text_value


def localize_table(table: Any, lang: str) -> Any:
    mapping = TABLE_COLUMNS.get(lang, {})
    if not mapping:
        return table
    if hasattr(table, "rename"):
        return table.rename(columns=mapping)
    if isinstance(table, list):
        return [{mapping.get(key, key): value for key, value in row.items()} for row in table]
    return table


